# Generated by Django 2.0.2 on 2020-01-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_adress1',
            new_name='shipping_address1',
        ),
    ]
